pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }
    tools {
        jdk 'jdk-17'
        maven 'maven'
    }
    environment {
        ANSIBLE_SERVER_IP=""
    }
    stages {
        stage('Compile source code...') {
            steps {
                script {
                    echo "compiling source code..."
                    dir('app/spring-petclinic') {
                        sh 'mvn clean compile'
                    }
                }
            }
        }
        stage('Run test...') {
            steps {
                script {
                    echo "running tests on source code..."
                    dir('app/spring-petclinic') {
                        sh 'mvn clean test'
                    }
                }
            }
        }
        stage('Build jar') {
            steps {
                script {
                    echo "building jar..."
                    dir('app') {
                        sh 'mvn clean package'
                    }
                }
            }
        }
        stage('Copy files to ansible server') {
            steps {
                script {
                    echo 'copying jar file to ansible server...'
                    def server = "ubuntu@${ANSIBLE_SERVER_IP}" 
                    //def copyCmd = "cp app/spring-petclinic/target/spring-petclinic-1.0.0-SNAPSHOT.jar ~/ansible-dir/"
                    sshagent(['ansible-server-ssh-key']) {
                        sh "scp app/spring-petclinic/target/spring-petclinic-1.0.0-SNAPSHOT.jar ${server}:~/ansible-dir/"  //May need to add the `-o StrictHostKeyChecking=no` flag
                        //sh "ssh -o StrictHostKeyChecking=no ${server} ${copyCmd}"  Alternative command to copy the jar file to ansible server
                    }
                }
            }
        }
    }
}